# Generated by Django 3.2.12 on 2022-02-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Name')),
                ('salary', models.CharField(max_length=20, verbose_name='Salary')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateField(verbose_name='Data')),
            ],
        ),
    ]
