# Generated by Django 4.0.1 on 2022-04-06 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameAcc', models.CharField(max_length=100, verbose_name='Username')),
                ('psswdAcc', models.CharField(max_length=100, verbose_name='Password')),
                ('emailAcc', models.EmailField(max_length=200, verbose_name='Email')),
                ('telephoneAcc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telephone')),
                ('aboutCompAcc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='About company')),
                ('logoCompAcc', models.ImageField(blank=True, null=True, upload_to='companies_photo/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, verbose_name='Roles Name')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('salary', models.CharField(max_length=20, verbose_name='Salary')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateField(verbose_name='Data')),
                ('Imagesrs', models.CharField(max_length=50, verbose_name='Imageurl')),
                ('Telephonenumber', models.CharField(max_length=20, verbose_name='Telephonenumber')),
                ('complaint', models.IntegerField(verbose_name='Complaint')),
                ('accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateField(verbose_name='Data')),
                ('experience', models.CharField(max_length=100, verbose_name='Experience')),
                ('imagesrs', models.CharField(max_length=50, verbose_name='Imageurl')),
                ('telephonenumber', models.CharField(max_length=20, verbose_name='Telephonenumber')),
                ('complaint', models.CharField(blank=True, max_length=20, null=True, verbose_name='Complaint')),
                ('accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.accounts')),
            ],
        ),
        migrations.AddField(
            model_name='accounts',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roles'),
        ),
    ]
