# Generated by Django 3.2.12 on 2022-02-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='Imagesrs',
            field=models.TextField(default=1, verbose_name='ImageSrs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
