# Generated by Django 3.2.12 on 2022-02-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220221_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='Telephonenumber',
            field=models.TextField(default=1, verbose_name='Telephonenumber'),
            preserve_default=False,
        ),
    ]
