# Generated by Django 3.2.12 on 2022-02-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_vacancies_telephonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='email',
            field=models.CharField(default=1, max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='Imagesrs',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='Telephonenumber',
            field=models.CharField(max_length=20, verbose_name='Telephonenumber'),
        ),
    ]
