# Generated by Django 3.2.12 on 2022-02-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_vacancies_imagesrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('text', models.TextField(verbose_name='Text')),
                ('date', models.DateField(verbose_name='Data')),
                ('experience', models.CharField(max_length=100, verbose_name='Experience')),
                ('Imagesrs', models.CharField(max_length=50, verbose_name='Imageurl')),
                ('Telephonenumber', models.CharField(max_length=20, verbose_name='Telephonenumber')),
            ],
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
