# Generated by Django 3.2.12 on 2022-02-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220224_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
